#!/usr/bin/env node

var Bolt = require('misfit-bolt');
var timeout = 3000;

var config = {
  platform: "MisfitBolt",
  name: "MisfitBolt",
  accessories: []
};

console.log('Discovering Bolts...');
Bolt.discover(function(bolt) {
  console.log('New Bolt discovered');
  config.accessories.push({id: bolt.id, name: 'changeme'});
});

setTimeout(function() {
  console.log('\n\nCopy the following block in your platform entry in ~/.homebridge/config.json\n');
  console.log(JSON.stringify(config, null, '  '));
  console.log('\n');
  process.exit(0);
}, timeout);
